export interface Colors {
  text: string
  lightMist: string
  oceanMist: string
  white: string
  blueSapphire: string
  deepOrange: string
  ghostWhite: string
  gray: string
  lightYellow: string
  lightTransparentBlack: string
  midnightGlow: string
  inputBackground: string
  black: string
  labelButton: string
  skyLight: string
  oceanTeal: string
  placeholderColor: string
  blue: string
  spaceCadet: string
  yellow: string
  mistWhite: string
  sunsetOrange: string
  smokeStone: string
  tealGreen: string
  lightSunset: string
  bookingDetailsBackgroundCard: string
  lightSilver: string
  radioColor: string
  green: string
  red: string
  blueOTP: string
  lightGreen: string
  lightRed: string
  lightGray: string
  borderInputaOTP: string
  midnightBlue: string
  textDate: string
  bgDate: string
  bgInput: string
  bgSearch: string
}
